version: '3'
services:

  alias_db:
    image: postgres:13
    restart: always
    container_name: alias_db
    env_file:
      - .env
    networks:
      - alias-network
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - alias_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}


  alias_web:
    container_name: alias_web
    image: alias-server
    build:
      context: .
      dockerfile: dockerfiles/docker_django.conf
    env_file:
      - .env
    depends_on:
      - alias_db
    networks:
      - alias-network
    volumes:
      - sock:/sock
      - staticfiles:/app/staticfiles
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: bash -c "sh run_web.sh && uwsgi --ini uwsgi.ini"


  alias_nginx:
    restart: always
    container_name: alias_nginx
    build:
      context: .
      dockerfile: dockerfiles/docker_nginx.conf
    env_file:
      - .env
    ports:
      - "127.0.0.1:${APP_PORT}:80"
    expose:
      - 80
    depends_on:
      - alias_web
    networks:
      - alias-network
    volumes:
      - sock:/sock
      - staticfiles:/staticfiles


  alias_docker:
    container_name: alias_docker
    build:
      context: .
      dockerfile: dockerfiles/docker_django.conf
    env_file:
      - .env
    ports:
      - "${APP_HOST}:${APP_PORT}:8000"
    depends_on:
      - alias_db
    networks:
      - alias-network
    volumes:
      - staticfiles:/app/staticfiles
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: bash -c "sh run_web.sh && python manage.py runserver ${APP_HOST}:${APP_PORT}"


networks:
  alias-network:
    external: false

volumes:
  staticfiles:
    external: false

  sock:
    external: false

  alias_db_volume:
    external: false
