# Generated by Django 3.2.5 on 2021-07-31 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_room", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EasyWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=30, unique=True)),
                (
                    "img",
                    models.CharField(
                        default="https://pixabay.com/get/g4b09d9e0d046b094964dc9977fdc17ef984ffc0a09a6b0f4947ab5bff0448dfe1e40a4a4c3fed4d594931b0d4c5d0f5b2b17e7561f3f44e90845bc30eca2df21_640.jpg",
                        max_length=150,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HardWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=30, unique=True)),
                (
                    "img",
                    models.CharField(
                        default="https://pixabay.com/get/g4b09d9e0d046b094964dc9977fdc17ef984ffc0a09a6b0f4947ab5bff0448dfe1e40a4a4c3fed4d594931b0d4c5d0f5b2b17e7561f3f44e90845bc30eca2df21_640.jpg",
                        max_length=150,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediumWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=30, unique=True)),
                (
                    "img",
                    models.CharField(
                        default="https://pixabay.com/get/g4b09d9e0d046b094964dc9977fdc17ef984ffc0a09a6b0f4947ab5bff0448dfe1e40a4a4c3fed4d594931b0d4c5d0f5b2b17e7561f3f44e90845bc30eca2df21_640.jpg",
                        max_length=150,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=30)),
                (
                    "img",
                    models.CharField(
                        default="https://pixabay.com/get/g4b09d9e0d046b094964dc9977fdc17ef984ffc0a09a6b0f4947ab5bff0448dfe1e40a4a4c3fed4d594931b0d4c5d0f5b2b17e7561f3f44e90845bc30eca2df21_640.jpg",
                        max_length=150,
                    ),
                ),
                ("guess", models.IntegerField(default=0)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_words",
                        to="game_room.room",
                    ),
                ),
            ],
        ),
    ]
