# Generated by Django 3.2.5 on 2021-07-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="easyword",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="easyword",
            name="img",
            field=models.CharField(
                default="https://pixabay.com/get/g4b09d9e0d046b094964dc9977fdc17ef984ffc0a09a6b0f4947ab5bff0448dfe1e40a4a4c3fed4d594931b0d4c5d0f5b2b17e7561f3f44e90845bc30eca2df21_640.jpg",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="easyword",
            name="word",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="hardword",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="hardword",
            name="img",
            field=models.CharField(
                default="https://pixabay.com/get/g4b09d9e0d046b094964dc9977fdc17ef984ffc0a09a6b0f4947ab5bff0448dfe1e40a4a4c3fed4d594931b0d4c5d0f5b2b17e7561f3f44e90845bc30eca2df21_640.jpg",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="hardword",
            name="word",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="mediumword",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mediumword",
            name="img",
            field=models.CharField(
                default="https://pixabay.com/get/g4b09d9e0d046b094964dc9977fdc17ef984ffc0a09a6b0f4947ab5bff0448dfe1e40a4a4c3fed4d594931b0d4c5d0f5b2b17e7561f3f44e90845bc30eca2df21_640.jpg",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mediumword",
            name="word",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="word",
            name="img",
            field=models.CharField(
                default="https://pixabay.com/get/g4b09d9e0d046b094964dc9977fdc17ef984ffc0a09a6b0f4947ab5bff0448dfe1e40a4a4c3fed4d594931b0d4c5d0f5b2b17e7561f3f44e90845bc30eca2df21_640.jpg",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
